on:
  push:
    branches:
      - master 









jobs:
  build:
    runs_on: ubuntu-latest

    steps:
      - name: 'Testing Github action'
        run: pwd

      -name: 'Testing Printing'
        run: echo Fawzy 