name: Build and Deploy Website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t your_image_name:tag .

      - name: Run Docker Container
        run: docker run -d -p 8080:80 your_image_name:tag
